media:
  input: public
  output: /

content:
  - name: blog
    label: Blog Posts
    type: collection
    path: src/content/blog
    view:
      fields: [ title, pubDate, draft ]
    fields:
      - name: title
        label: Title
        type: text
        required: true

      - name: author
        label: Author
        type: text
        required: true

      - name: pubDate
        label: Publish Date
        type: date
        required: true

      - name: heroImage
        label: Hero Image
        type: file
        required: false

      - name: draft
        label: Draft
        type: boolean
        required: false

      - name: body
        label: Body
        type: code
        options:
          language: markdown
        required: true