media:
  input: public
  output: /

content:
  - name: posts
    label: ブログ記事
    folder: src/content/posts
    extension: md
    create: true
    delete: true
    slug:  "{{title | slug}}"
    fields:
      - name: title
        label: タイトル
        type: text
        required: true

      - name: description
        label: 概要
        type: text

      - name: date
        label: 投稿日
        type: datetime
        required: true
        default: now

      - name: categories
        label: カテゴリ
        type: list
        field:
          type: text

      - name: tags
        label: タグ
        type: list
        field:
          type: text

      - name: draft
        label: 下書き
        type: boolean
        default: false

      - name: body
        label: 本文
        type: code
        options:
          language: markdown
        required: true