content:
  - name: posts
    label: Blog Posts
    path: src/content/posts
    type: collection
    filename: "{fields.date}-{fields.title | slug}.md"
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: markdown
        required: true