content:
  - name: posts
    label: Blog Posts
    folder: src/content/posts
    extension: md
    slug: "test-post"
    fields:
      - name: title
        label: Title
        type: text
        required: true
      - name: body
        label: Body
        type: markdown
        required: true