media:
  input: public
  output: /

content:
  - name: posts
    label: Blog Posts
    path: src/content/posts
    type: collection
    filename: "{fields.date}-{fields.title | slug}.md"
    fields:
      - name: title
        label: Title
        type: text
        required: true

      - name: author
        label: Author
        type: text
        required: true

      - name: cover
        label: Cover Image
        type: file
        required: false

      - name: body
        label: Body
        type: code
        options:
          language: markdown
        required: true